from ass import db, Crop


crops = { 	'Plum':
					{ 
					'variety':'tomato',
				 	'family':'fruit',
					'yield':2.8,
					'space_x':0.25,
					'space_y':0.25,
					'density':'',
					'fruit_quantity':26,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'iceberg': 
					{
					'variety':'lettuce',
				 	'family':'leafy',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'arugula':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					}, 

			'radicchio':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'bell_pepper':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'cabbage':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'coriander':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'basil':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'squash':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'chive':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'sweet_corn':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'black_bean':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'strawberry':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'tomato2':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'rice':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'chilli':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					},

			'cottom':
					{
					'variety':'something',
				 	'family':'something',
					'yield':0,
					'space_x':0,
					'space_y':0,
					'density':0,
					'fruit_quantity':0,
					'fruit_size':0,
					'fruit_weight':0,
					'water':0,
					'nutrient':0,
					'radiation':0,
					'cycle_dtg_days':0,
					'cycle_dtm_days':0,
					'soil_ph_min':0, 		'soil_ph_opt':0, 		'soil_ph_max':0,
					'soil_temp_min':0,		'soil_temp_opt':0,		'soil_temp_max':0,
					'soil_humi_min':0,		'soil_humi_opt':0,		'soil_humi_max':0,
					'soil_nutrient_min':0,	'soil_nutrient_opt':0,	'soil_nutrient_max':0,
					'air_temp_min':0,		'air_temp_opt':0,		'air_temp_max':0,
					'air_humi_min':0,		'air_humi_opt':0,		'air_humi_max':0,
					}
		}

# def calc_density(crop):
# 	density = (crops[crop]['space_x']) * (crops[crop]['space_y'])
# 	return density

# def add_crop(*args, **kwargs):
# 	print (args)
# 	print ()
# 	print (kwargs)