from ass import db, Crop

crops = { 	
			'plum':
					{
					'_name':'plum',
					'_variety':'tomato',
				 	'_family':'fruit',
					'_yield':2800, # gr
					'_space_x':30, # cm
					'_space_y':30, # cm
					'_space_z':1.1, # m
					'_density':0.001111, # plants/cm2
					'_fruit_quantity':26,
					'_fruit_size':7.6, # cm
					'_fruit_weight':62, # gr
					'_water':1000, # ml/day
					'_nutrient':18, # mSiemens
					'_radiation':720, # min/day
					'_dtg':12, # day
					'_dtm':180, # day
					'_soil_ph_min':6, 		'_soil_ph_opt':6.5, 		'_soil_ph_max':6.8,			# pH
					'_soil_temp_min':15,	'_soil_temp_opt':23,		'_soil_temp_max':30, 		# C
					'_soil_humi_min':50,	'_soil_humi_opt':60,		'_soil_humi_max':75, 		# %RH
					'_soil_nutrient_min':2,	'_soil_nutrient_opt':16,	'_soil_nutrient_max':40,	# mSiemens
					'_air_temp_min':17,		'_air_temp_opt':25,			'_air_temp_max':28, 		# C
					'_air_humi_min':60,		'_air_humi_opt':63,			'_air_humi_max':70,			# %RH
					},
			'romaine': 
					{
					'_name':'romaine',
					'_variety':'lettuce',
				 	'_family':'leafy',
					'_yield':626,
					'_space_x':20,
					'_space_y':20,
					'_space_z':35,
					'_density':0.0025,
					'_fruit_quantity':1,
					'_fruit_size':35,
					'_fruit_weight':626,
					'_water':800,
					'_nutrient':0.8,
					'_radiation':680,
					'_dtg':10,
					'_dtm':70,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.2, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':40,	'_soil_humi_opt':45,	'_soil_humi_max':60,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':16,		'_air_temp_max':19,
					'_air_humi_min':60,		'_air_humi_opt':65,		'_air_humi_max':70,
					},
			'arugula':
					{
					'_name':'arugula',
					'_variety':'herb',
				 	'_family':'leafy',
					'_yield':0.671,
					'_space_x':2.04,
					'_space_y':2.04,
					'_space_z':30,
					'_density':0.240292,
					'_fruit_quantity':1,
					'_fruit_size':25,
					'_fruit_weight':0.671,
					'_water':50,
					'_nutrient':0.5,
					'_radiation':600,
					'_dtg':6,
					'_dtm':47,
					'_soil_ph_min':6, 		'_soil_ph_opt':6.3, 	'_soil_ph_max':6.8,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':10,		'_air_temp_opt':18,		'_air_temp_max':26,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					}, 
			'radicchio':
					{
					'_name':'radicchio',
					'_variety':'unknown',
				 	'_family':'leafy',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'bell pepper':
					{
					'_name':'bell pepper',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'cabbage':
					{
					'_name':'cabbage',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'coriander':
					{
					'_name':'coriander',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'basil':
					{
					'_name':'basil',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'squash':
					{
					'_name':'squash',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'chive':
					{
					'_name':'chive',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'sweet corn':
					{
					'_name':'sweet corn',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'black bean':
					{
					'_name':'black bean',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'strawberry':
					{
					'_name':'strawberry',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'plum2':
					{
					'_name':'plum2',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'rice':
					{
					'_name':'rice',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'chilli':
					{
					'_name':'chilli',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
			'cottom':
					{
					'_name':'cottom',
					'_variety':'something',
				 	'_family':'something',
					'_yield':0,
					'_space_x':0,
					'_space_y':0,
					'_space_z':0,
					'_density':0,
					'_fruit_quantity':0,
					'_fruit_size':0,
					'_fruit_weight':0,
					'_water':0,
					'_nutrient':0,
					'_radiation':0,
					'_dtg':0,
					'_dtm':0,
					'_soil_ph_min':0, 		'_soil_ph_opt':0, 		'_soil_ph_max':0,
					'_soil_temp_min':0,		'_soil_temp_opt':0,		'_soil_temp_max':0,
					'_soil_humi_min':0,		'_soil_humi_opt':0,		'_soil_humi_max':0,
					'_soil_nutrient_min':0,	'_soil_nutrient_opt':0,	'_soil_nutrient_max':0,
					'_air_temp_min':0,		'_air_temp_opt':0,		'_air_temp_max':0,
					'_air_humi_min':0,		'_air_humi_opt':0,		'_air_humi_max':0,
					},
		}

# Automatically add crops to the db through SQLAlchemy
def add_crops(crops):
	print('Starting inserting crops to db')
	for crop in crops:
		crop_to_db = Crop(**crops[crop])
		db.session.add(crop_to_db)
	db.session.commit()
	print('Crops added to db! Done!')


# TO ADD THESE CROP DATASETS RUN:
if __name__ == '__main__':
	add_crops(crops)
