"""empty message

Revision ID: 18cbc40d5450
Revises: a33aa88d3918
Create Date: 2018-09-05 18:25:54.517321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cbc40d5450'
down_revision = 'a33aa88d3918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('welcome', sa.Column('add_soil_test', sa.Boolean(), nullable=True))
    op.add_column('welcome', sa.Column('add_water_test', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('welcome', 'add_water_test')
    op.drop_column('welcome', 'add_soil_test')
    # ### end Alembic commands ###
