"""adding agrisensor lat and long to table agrimodulesystem

Revision ID: 22c71c9659fe
Revises: 
Create Date: 2018-05-02 15:34:51.502572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c71c9659fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agrimodulesystem', sa.Column('_lat_agrisensor', sa.Float(precision=8), nullable=True))
    op.add_column('agrimodulesystem', sa.Column('_lon_agrisensor', sa.Float(precision=8), nullable=True))
    op.alter_column('agrimodulesystem', '_lat_agrimodule',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('agrimodulesystem', '_lon_agrimodule',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agrimodulesystem', '_lon_agrimodule',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('agrimodulesystem', '_lat_agrimodule',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.drop_column('agrimodulesystem', '_lon_agrisensor')
    op.drop_column('agrimodulesystem', '_lat_agrisensor')
    # ### end Alembic commands ###
