"""empty message

Revision ID: 35dcc9d63d72
Revises: 9428612363ae
Create Date: 2018-06-20 04:19:14.332835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35dcc9d63d72'
down_revision = '9428612363ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop', sa.Column('image', sa.String(length=200), nullable=True))
    op.add_column('crop', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('crop', sa.Column('time_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint('crop__image_key', 'crop', type_='unique')
    op.create_unique_constraint(None, 'crop', ['image'])
    op.drop_column('crop', '_time_updated')
    op.drop_column('crop', '_time_created')
    op.drop_column('crop', '_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop', sa.Column('_image', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('crop', sa.Column('_time_created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('crop', sa.Column('_time_updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'crop', type_='unique')
    op.create_unique_constraint('crop__image_key', 'crop', ['_image'])
    op.drop_column('crop', 'time_updated')
    op.drop_column('crop', 'time_created')
    op.drop_column('crop', 'image')
    # ### end Alembic commands ###
