"""empty message

Revision ID: 55f5021b08da
Revises: e6019fdd19f5
Create Date: 2018-06-26 21:19:13.576935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f5021b08da'
down_revision = 'e6019fdd19f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agrimodules', sa.Column('mac', sa.String(length=400), nullable=True))
    op.add_column('agrimodules', sa.Column('public_id', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agrimodules', 'public_id')
    op.drop_column('agrimodules', 'mac')
    # ### end Alembic commands ###
