"""migrating for the first time the db

Revision ID: 753eaef9f222
Revises: 
Create Date: 2018-05-07 20:35:45.846351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753eaef9f222'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agrimodulefbtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('msg', sa.Text(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contactustable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('msg', sa.Text(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_name', sa.String(length=25), nullable=False),
    sa.Column('_variety', sa.String(length=25), nullable=True),
    sa.Column('_family', sa.String(length=25), nullable=True),
    sa.Column('_yield', sa.Float(precision=3), nullable=True),
    sa.Column('_space_x', sa.Float(precision=2), nullable=True),
    sa.Column('_space_y', sa.Float(precision=2), nullable=True),
    sa.Column('_space_z', sa.Float(precision=2), nullable=True),
    sa.Column('_density', sa.Float(precision=2), nullable=True),
    sa.Column('_fruit_quantity', sa.Integer(), nullable=True),
    sa.Column('_fruit_size', sa.Float(precision=2), nullable=True),
    sa.Column('_fruit_weight', sa.Float(precision=2), nullable=True),
    sa.Column('_water', sa.Float(precision=4), nullable=True),
    sa.Column('_nutrient', sa.Float(precision=4), nullable=True),
    sa.Column('_radiation', sa.Float(precision=4), nullable=True),
    sa.Column('_dtg', sa.Integer(), nullable=True),
    sa.Column('_dtm', sa.Integer(), nullable=True),
    sa.Column('_soil_ph_min', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_ph_opt', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_ph_max', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_temp_min', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_temp_opt', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_temp_max', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_humi_min', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_humi_opt', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_humi_max', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_nutrient_min', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_nutrient_opt', sa.Float(precision=2), nullable=True),
    sa.Column('_soil_nutrient_max', sa.Float(precision=2), nullable=True),
    sa.Column('_air_temp_min', sa.Float(precision=2), nullable=True),
    sa.Column('_air_temp_opt', sa.Float(precision=2), nullable=True),
    sa.Column('_air_temp_max', sa.Float(precision=2), nullable=True),
    sa.Column('_air_humi_min', sa.Float(precision=2), nullable=True),
    sa.Column('_air_humi_opt', sa.Float(precision=2), nullable=True),
    sa.Column('_air_humi_max', sa.Float(precision=2), nullable=True),
    sa.Column('_time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('_time_updated', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_name')
    )
    op.create_table('newslettertable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platformfbtable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('msg', sa.Text(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('last_name', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mobile', sa.String(length=12), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=100), nullable=True),
    sa.Column('current_login_ip', sa.String(length=100), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('_time_updated', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile')
    )
    op.create_table('workwithustable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=True),
    sa.Column('msg', sa.Text(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agrimodulesystem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_identifier_agrimodulesystem', sa.String(length=50), nullable=False),
    sa.Column('_identifier_agrimodule', sa.String(length=50), nullable=False),
    sa.Column('_identifier_agripump', sa.String(length=50), nullable=False),
    sa.Column('_lat_agrimodule', sa.Float(precision=8), nullable=True),
    sa.Column('_lon_agrimodule', sa.Float(precision=8), nullable=True),
    sa.Column('_lat_agrisensor', sa.Float(precision=8), nullable=True),
    sa.Column('_lon_agrisensor', sa.Float(precision=8), nullable=True),
    sa.Column('_lat_agripump', sa.Float(precision=8), nullable=True),
    sa.Column('_lon_agripump', sa.Float(precision=8), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('_time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('_time_updated', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('_identifier_agrimodule'),
    sa.UniqueConstraint('_identifier_agrimodulesystem'),
    sa.UniqueConstraint('_identifier_agripump')
    )
    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('location', sa.String(length=20), nullable=True),
    sa.Column('cultivation_area', sa.Float(precision=2), nullable=True),
    sa.Column('cultivation_process', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('_time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('_time_updated', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pump',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=25), nullable=True),
    sa.Column('flow_rate', sa.Float(precision=2), nullable=False),
    sa.Column('height_max', sa.Float(), nullable=False),
    sa.Column('kwh', sa.Float(precision=2), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('_time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('_time_updated', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('agrimodule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('soil_ph', sa.Float(precision=4), nullable=True),
    sa.Column('soil_nutrient', sa.Float(precision=4), nullable=True),
    sa.Column('soil_temp', sa.Float(precision=4), nullable=True),
    sa.Column('soil_humi', sa.Float(precision=4), nullable=True),
    sa.Column('air_temp', sa.Float(precision=4), nullable=True),
    sa.Column('air_humi', sa.Float(precision=4), nullable=True),
    sa.Column('air_pres', sa.Float(precision=4), nullable=True),
    sa.Column('solar_radiation', sa.Float(precision=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agrimodulesystem_id', sa.Integer(), nullable=True),
    sa.Column('_time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('_time_updated', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['agrimodulesystem_id'], ['agrimodulesystem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agripump',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('_daily_water', sa.Float(precision=3), nullable=True),
    sa.Column('_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('_00_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_01_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_02_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_03_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_04_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_05_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_06_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_07_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_08_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_09_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_10_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_11_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_12_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_13_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_14_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_15_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_16_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_17_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_18_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_19_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_20_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_21_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_22_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('_23_HOUR', sa.Float(precision=1), nullable=True),
    sa.Column('agrimodulesystem_id', sa.Integer(), nullable=True),
    sa.Column('pump_id', sa.Integer(), nullable=True),
    sa.Column('_time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('_time_updated', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['agrimodulesystem_id'], ['agrimodulesystem.id'], ),
    sa.ForeignKeyConstraint(['pump_id'], ['pump.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('cultivation_area', sa.Float(precision=2), nullable=True),
    sa.Column('cultivation_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cultivation_finish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('_current_yield', sa.Float(precision=2), nullable=True),
    sa.Column('cultivation_state', sa.String(length=20), nullable=True),
    sa.Column('cultivation_type', sa.String(length=5), nullable=True),
    sa.Column('farm_id', sa.Integer(), nullable=True),
    sa.Column('_time_created', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('_time_updated', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crops_field',
    sa.Column('field_id', sa.Integer(), nullable=True),
    sa.Column('crop_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['field.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crops_field')
    op.drop_table('field')
    op.drop_table('agripump')
    op.drop_table('agrimodule')
    op.drop_table('roles_users')
    op.drop_table('pump')
    op.drop_table('farm')
    op.drop_table('agrimodulesystem')
    op.drop_table('workwithustable')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('platformfbtable')
    op.drop_table('newslettertable')
    op.drop_table('crop')
    op.drop_table('contactustable')
    op.drop_table('agrimodulefbtable')
    # ### end Alembic commands ###
