"""empty message

Revision ID: 9428612363ae
Revises: e4d10c9e42bb
Create Date: 2018-06-20 04:13:02.185144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9428612363ae'
down_revision = 'e4d10c9e42bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    op.add_column('crop', sa.Column('_image', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'crop', ['_image'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crop', type_='unique')
    op.drop_column('crop', '_image')
    op.drop_table('crop_image')
    # ### end Alembic commands ###
