"""added new field in crop yeild2

Revision ID: 9bd3f90ed5e6
Revises: 753eaef9f222
Create Date: 2018-05-07 21:22:06.654623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd3f90ed5e6'
down_revision = '753eaef9f222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crop', sa.Column('_yield2', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crop', '_yield2')
    # ### end Alembic commands ###
