"""empty message

Revision ID: bdde6b20d442
Revises: 9bd3f90ed5e6
Create Date: 2018-05-09 22:44:40.983290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdde6b20d442'
down_revision = '9bd3f90ed5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('email_rec', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('image', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('state', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=True))
    op.add_column('user', sa.Column('zipcode', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'zipcode')
    op.drop_column('user', 'username')
    op.drop_column('user', 'state')
    op.drop_column('user', 'image')
    op.drop_column('user', 'email_rec')
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
