"""empty message

Revision ID: e6019fdd19f5
Revises: 3c32128bf8b0
Create Date: 2018-06-21 19:21:14.557324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6019fdd19f5'
down_revision = '3c32128bf8b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('welcome', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'welcome', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'welcome', type_='foreignkey')
    op.drop_column('welcome', 'user_id')
    # ### end Alembic commands ###
